const express = require("express")
const router = express.Router()
const owner_controller = require("../controllers/owner.controller")
router.post("/addTable", owner_controller.addTable)
router.post("/:id", owner_controller.updateTable)
router.get("/viewTables", owner_controller.viewTables)
router.post("/addDish", owner_controller.addDish)
router.post("/:id", owner_controller.updateMenu)
router.get("/viewMenu", owner_controller.viewMenu)
router.post("/addEmployee", owner_controller.addEmployee)
router.post("/:id", owner_controller.updateEmployee)
router.get("/viewEmployees", owner_controller.viewEmployees)
router.get("/viewOrders", owner_controller.viewOrders)
router.get("/viewBills", owner_controller.viewBills)
module.exports = router;
