const express = require("express")
const router = express.Router()
const owner_controller = require("../controllers/owner.controller")
const auth = require("../middlewares/auth");
router.post("/signup", owner_controller.signup)
router.post("/mail",auth, owner_controller.verifymail)
router.post("/Table",auth, owner_controller.addTable)
router.put("/Table",auth, owner_controller.updateTable)
router.delete("/Table",auth, owner_controller.deleteTable)
router.get("/Tables",auth, owner_controller.viewTables)
router.post("/employeemailid",auth, owner_controller.addemployeemailid)
router.post("/mailid",auth, owner_controller.verifyemployeemailid)
router.post("/Employee",auth,owner_controller.addEmployee)
router.put("/Employee",auth,owner_controller.updateEmployee)
router.delete("/Employee",auth,owner_controller.deleteEmployee)
router.get("/Employees",auth, owner_controller.viewEmployees)
router.post("/Dish",auth, owner_controller.addDish)
router.put("/Dish",auth, owner_controller.updateDish)
router.get("/Dishes",auth, owner_controller.viewDishes)
router.delete("/Dish",auth, owner_controller.deleteDish)
module.exports = router