const express = require("express")
const router = express.Router()
const waiter_controller = require("../controllers/waiter.controller")
router.get("/viewTables", waiter_controller.viewTables)
router.post("/updateStatus", waiter_controller.updateStatus)
router.get("/viewMenu", waiter_controller.viewMenu)
router.get("/viewOrder", waiter_controller.viewOrder)
router.post("/takeOrder", waiter_controller.takeOrder)
router.post("/updateOrder", waiter_controller.updateOrder)
router.post("/generateOTP", waiter_controller.generateOTP)
router.post("/updateCustomerdetails", waiter_controller.updateCustomerdetails)